[project]
name = "Practical-Tools"
description = "To enhance the usability of ComfyUI, optimizations and integrations have been implemented for several commonly used nodes."
version = "1.0.7"

[project.urls]
Repository = "https://github.com/wenchengxiang/ComfyUI-Practical-Tools"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "wcx"
DisplayName = "ComfyUI-Practical-Tools"