[project]
name = "ComfyUI-WCXnodes"
description = "To enhance the usability of ComfyUI, optimizations and integrations have been implemented for several commonly used nodes."
version = "1.0.260808"

[project.urls]
Repository = "https://github.com/wenchengxiang/ComfyUI-WCXnodes"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "wcx"
DisplayName = "ComfyUI-WCXnodes"